[book]
authors = ["Syrac organization"]
language = "en"
src = "src/en"
title = "Syrac"

[build]
create-missing = false

[output.html]
additional-js = ["theme/appbutton.js"]
default-theme = "light"
preferred-dark-theme = "ayu"
